/**
 * OpenClaw plugin entry point for SparkUI.
 *
 * This file is loaded by OpenClaw when the plugin is installed via:
 *   openclaw plugins install @limeade-labs/sparkui
 *
 * It wraps the existing SparkUI Express server and exposes it as a
 * managed service within the OpenClaw plugin lifecycle.
 *
 * v1.5.0 — Completion event routing (#422):
 *   - Tracks originating session/channel when pages are created
 *   - Subscribes to server eventBus for completion events
 *   - Routes formatted event summaries back to originating chat
 *
 * v1.4.0 — Zero-config sprint:
 *   - Token auto-persistence to OpenClaw config
 *   - Native agent tools (sparkui_push, sparkui_compose)
 *   - Gateway proxy routes (/sparkui/*)
 *   - Public URL auto-detection from gateway config
 *   - Redis graceful fallback
 */

import { definePluginEntry } from "openclaw/plugin-sdk/plugin-entry";
import { createRequire } from "node:module";
import { randomBytes } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

/** Resolve a push token: config → env → generate (returns { token, autoGenerated }) */
function resolvePushToken(configToken) {
  if (configToken) return { token: configToken, autoGenerated: false };
  if (process.env.PUSH_TOKEN) return { token: process.env.PUSH_TOKEN, autoGenerated: false };
  return { token: "spk_" + randomBytes(24).toString("hex"), autoGenerated: true };
}

/**
 * Resolve the public URL for shareable links.
 * Without a gateway proxy, the SparkUI server runs on its own port —
 * so gateway domain detection is not useful unless the user has their own reverse proxy.
 */
function resolvePublicUrl(pluginConfig, port) {
  // 1. Explicit plugin config (highest priority)
  if (pluginConfig?.publicUrl) return pluginConfig.publicUrl;

  // 2. Environment variable
  if (process.env.SPARKUI_BASE_URL) return process.env.SPARKUI_BASE_URL;

  // 3. Fallback — null signals localhost fallback (caller logs a helpful message)
  return null;
}

export default definePluginEntry({
  id: "sparkui",
  name: "SparkUI",
  description:
    "Ephemeral, purpose-built web UIs generated on demand from chat conversations",

  register(api) {
    const config = api.pluginConfig ?? {};
    const port =
      config.port ?? (parseInt(process.env.SPARKUI_PORT, 10) || 3457);
    const redisUrl = config.redisUrl ?? process.env.REDIS_URL ?? null;

    // Token and public URL are resolved here but may be overridden in start()
    let pushToken = null;
    let resolvedPublicUrl = null;
    let serverRef = null;
    let serverReady = false;
    let eventBusRef = null;

    // Map pageId → { sessionId, channelId } for routing events back
    const pageSessionMap = new Map();

    // ── Managed Service ─────────────────────────────────────────────────

    api.registerService({
      id: "sparkui-server",
      name: "SparkUI Server",

      async start() {
        // Resolve token (may persist to config)
        const { token, autoGenerated } = resolvePushToken(config.pushToken);
        pushToken = token;

        // Persist auto-generated token to OpenClaw config
        if (autoGenerated) {
          api.log?.info?.(
            `SparkUI push token (auto-generated): ${pushToken.slice(0, 8)}...${pushToken.slice(-4)} (full token saved to OpenClaw config)`
          );
          try {
            const cfg = await api.runtime.config.loadConfig();
            if (!cfg.plugins) cfg.plugins = {};
            if (!cfg.plugins.entries) cfg.plugins.entries = {};
            if (!cfg.plugins.entries.sparkui) cfg.plugins.entries.sparkui = {};
            if (!cfg.plugins.entries.sparkui.config)
              cfg.plugins.entries.sparkui.config = {};
            cfg.plugins.entries.sparkui.config.pushToken = pushToken;
            await api.runtime.config.writeConfigFile(cfg);
            api.log?.info?.(
              `SparkUI push token persisted to config (first run)`
            );
          } catch (err) {
            api.log?.warn?.(
              `SparkUI: could not persist push token to config: ${err.message}`
            );
          }
        }

        // Resolve public URL
        resolvedPublicUrl = resolvePublicUrl(config, port);
        if (!resolvedPublicUrl) {
          resolvedPublicUrl = `http://localhost:${port}`;
          api.log?.info?.(`SparkUI: using localhost URLs. For shareable links, set publicUrl in plugin config.`);
        }

        // Auto-configure OpenClaw hooks for completion event routing
        const hooksToken = api.config?.hooks?.token;
        const gatewayPort = api.config?.gateway?.bind?.port ?? 18789;
        if (hooksToken) {
          process.env.OPENCLAW_HOOKS_URL = process.env.OPENCLAW_HOOKS_URL || `http://127.0.0.1:${gatewayPort}/hooks/agent`;
          process.env.OPENCLAW_HOOKS_TOKEN = process.env.OPENCLAW_HOOKS_TOKEN || hooksToken;
          api.log?.info?.('SparkUI: auto-configured OpenClaw hooks for completion event routing');
        } else {
          api.log?.info?.('SparkUI: hooks.token not found in config — completion events won\'t route to chat. Enable hooks in OpenClaw config.');
        }

        // Set env vars so server.js picks them up
        process.env.SPARKUI_PORT = String(port);
        process.env.PUSH_TOKEN = pushToken;
        if (resolvedPublicUrl) process.env.SPARKUI_BASE_URL = resolvedPublicUrl;
        if (redisUrl) process.env.REDIS_URL = redisUrl;

        // Import and start the server
        try {
          process.env._SPARKUI_PLUGIN_MODE = '1';
          const sparkui = require(resolve(__dirname, "server.js"));
          serverRef = sparkui.server;
          eventBusRef = sparkui.eventBus || null;

          // Wait for server to actually be listening
          await new Promise((resolve, reject) => {
            if (serverRef.listening) return resolve();

            const onListening = () => { cleanup(); resolve(); };
            const onError = (err) => { cleanup(); reject(err); };
            const timeout = setTimeout(() => {
              cleanup();
              reject(new Error('Server start timeout (30s)'));
            }, 30000);

            function cleanup() {
              serverRef.removeListener('listening', onListening);
              serverRef.removeListener('error', onError);
              clearTimeout(timeout);
            }

            serverRef.once('listening', onListening);
            serverRef.once('error', onError);
          });

          serverReady = true;

          // Subscribe to completion events from the server's in-process event bus
          if (eventBusRef) {
            eventBusRef.on('sparkui:event', (evt) => {
              handleSparkuiEvent(evt);
            });
            api.log?.info?.('SparkUI: completion event routing active');
          }

          api.log?.info?.(
            `SparkUI server started on port ${port}` +
              (resolvedPublicUrl
                ? ` (public: ${resolvedPublicUrl})`
                : "")
          );
        } catch (err) {
          if (err.code === "EADDRINUSE") {
            api.log?.error?.(
              `SparkUI: port ${port} is already in use. ` +
                `Set a different port in plugin config or SPARKUI_PORT env var.`
            );
          } else if (
            redisUrl &&
            (err.code === "ECONNREFUSED" || err.message?.includes("Redis"))
          ) {
            api.log?.warn?.(
              `SparkUI: Redis connection failed (${redisUrl}). ` +
                `The server may still start in in-memory mode.`
            );
          } else {
            api.log?.error?.(`SparkUI failed to start: ${err.message}`);
          }
          throw err;
        }
      },

      async stop() {
        if (eventBusRef) {
          eventBusRef.removeAllListeners('sparkui:event');
          eventBusRef = null;
        }
        pageSessionMap.clear();
        if (serverRef) {
          return new Promise((res) => {
            const timeout = setTimeout(() => {
              serverReady = false;
              serverRef = null;
              res();
            }, 5000);
            timeout.unref();

            serverRef.close(() => {
              clearTimeout(timeout);
              serverReady = false;
              serverRef = null;
              api.log?.info?.("SparkUI server stopped");
              res();
            });
          });
        }
      },

      inspect() {
        return {
          status: serverReady ? "running" : "stopped",
          port,
          pushToken: pushToken
            ? pushToken.slice(0, 8) + "..." + pushToken.slice(-4)
            : "(not yet resolved)",
          publicUrl: resolvedPublicUrl ?? `http://localhost:${port}`,
          redis: redisUrl ? "configured" : "not configured (in-memory mode)",
        };
      },
    });

    // ── Gateway Health Route ────────────────────────────────────────────

    api.registerHttpRoute({
      path: "/plugins/sparkui/status",
      auth: "plugin",
      handler: async (_req, res) => {
        const send = (code, obj) => {
          res.statusCode = code;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify(obj));
        };
        if (!serverReady) {
          send(503, { status: "stopped" });
          return true;
        }
        send(200, {
          status: "running",
          port,
          publicUrl: resolvedPublicUrl ?? `http://localhost:${port}`,
          redis: redisUrl ? "configured" : "in-memory",
        });
        return true;
      },
    });

    // ── Native Agent Tools ──────────────────────────────────────────────

    api.registerTool({
      name: "sparkui_push",
      description:
        "Create an ephemeral web page from a template. Returns a shareable URL. Use for dashboards, forms, polls, trackers, checkout flows — anything visual that's better as a web page than chat text.",
      parameters: {
        type: "object",
        properties: {
          template: {
            type: "string",
            description:
              "Template name: macro-tracker, checkout, workout-timer, feedback-form, poll, shopping-list, calendar, comparison, approval-flow, analytics-dashboard, ws-test",
          },
          data: {
            type: "object",
            additionalProperties: true,
            description: "Template-specific data object",
          },
          ttl: {
            type: "number",
            description: "Time to live in seconds (default: 3600)",
          },
        },
        required: ["template", "data"],
      },
      async execute(_id, params, context) {
        if (!serverReady || !pushToken) {
          return {
            content: [
              {
                type: "text",
                text: "SparkUI server is not running. Wait for it to start.",
              },
            ],
          };
        }
        try {
          const body = { ...params };
          // Auto-inject openclaw config for event routing
          // Skip if user explicitly set openclaw (including false/null to disable)
          if (body.openclaw === undefined) {
            const session = context?.session ?? api.session ?? null;
            const destination = session?.channelId ?? session?.to ?? null;
            if (destination) {
              body.openclaw = {
                enabled: true,
                eventTypes: ['completion'],
                channel: session?.channel ?? null,
                to: destination,
              };
            } else {
              api.log?.warn?.("SparkUI: no session channel context — completion events won't route for this page");
            }
          }

          const resp = await fetch(`http://localhost:${port}/api/push`, {
            method: "POST",
            headers: {
              Authorization: `Bearer ${pushToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify(body),
          });
          const result = await resp.json();
          if (!resp.ok) {
            return {
              content: [
                {
                  type: "text",
                  text: `SparkUI error: ${JSON.stringify(result)}`,
                },
              ],
            };
          }

          // Track originating session for completion event routing
          if (result.id) {
            const session = context?.session ?? api.session ?? null;
            if (session) {
              pageSessionMap.set(result.id, {
                sessionId: session.id ?? session.sessionId ?? null,
                channelId: session.channelId ?? session.channel ?? null,
                template: params.template || null,
              });
            }
          }

          const baseUrl = resolvedPublicUrl || `http://localhost:${port}`;
          const fullUrl = `${baseUrl}${result.url}`;
          return {
            content: [
              {
                type: "text",
                text: JSON.stringify({ ...result, fullUrl }),
              },
            ],
          };
        } catch (err) {
          return {
            content: [
              { type: "text", text: `SparkUI fetch error: ${err.message}` },
            ],
          };
        }
      },
    });

    api.registerTool({
      name: "sparkui_compose",
      description:
        "Compose a custom web page from reusable components (header, button, timer, checklist, progress, stats, form, tabs). Returns a shareable URL.",
      parameters: {
        type: "object",
        properties: {
          title: {
            type: "string",
            description: "Page title",
          },
          sections: {
            type: "array",
            items: {
              type: "object",
              properties: {
                type: {
                  type: "string",
                  description:
                    "Component type: header, button, timer, checklist, progress, stats, form, tabs",
                },
                config: {
                  type: "object",
                  additionalProperties: true,
                  description: "Component-specific config",
                },
              },
              required: ["type", "config"],
            },
            description: "Array of component sections",
          },
          ttl: {
            type: "number",
            description: "Time to live in seconds (default: 3600)",
          },
        },
        required: ["title", "sections"],
      },
      async execute(_id, params, context) {
        if (!serverReady || !pushToken) {
          return {
            content: [
              {
                type: "text",
                text: "SparkUI server is not running. Wait for it to start.",
              },
            ],
          };
        }
        try {
          const body = { ...params };
          // Auto-inject openclaw config for event routing
          // Skip if user explicitly set openclaw (including false/null to disable)
          if (body.openclaw === undefined) {
            const session = context?.session ?? api.session ?? null;
            const destination = session?.channelId ?? session?.to ?? null;
            if (destination) {
              body.openclaw = {
                enabled: true,
                eventTypes: ['completion'],
                channel: session?.channel ?? null,
                to: destination,
              };
            } else {
              api.log?.warn?.("SparkUI: no session channel context — completion events won't route for this page");
            }
          }

          const resp = await fetch(`http://localhost:${port}/api/compose`, {
            method: "POST",
            headers: {
              Authorization: `Bearer ${pushToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify(body),
          });
          const result = await resp.json();
          if (!resp.ok) {
            return {
              content: [
                {
                  type: "text",
                  text: `SparkUI error: ${JSON.stringify(result)}`,
                },
              ],
            };
          }

          // Track originating session for completion event routing
          if (result.id) {
            const session = context?.session ?? api.session ?? null;
            if (session) {
              pageSessionMap.set(result.id, {
                sessionId: session.id ?? session.sessionId ?? null,
                channelId: session.channelId ?? session.channel ?? null,
                template: null,
              });
            }
          }

          const baseUrl = resolvedPublicUrl || `http://localhost:${port}`;
          const fullUrl = `${baseUrl}${result.url}`;
          return {
            content: [
              {
                type: "text",
                text: JSON.stringify({ ...result, fullUrl }),
              },
            ],
          };
        } catch (err) {
          return {
            content: [
              { type: "text", text: `SparkUI fetch error: ${err.message}` },
            ],
          };
        }
      },
    });

    // ── Completion Event Routing ───────────────────────────────────────

    /**
     * Format a completion event into a human-readable summary for chat.
     */
    function formatEventSummary(evt) {
      const { type, data, template, title } = evt;
      const pageLabel = title || template || 'page';

      if (type !== 'completion') {
        return `[SparkUI] Event on "${pageLabel}": ${type}`;
      }

      switch (template) {
        case 'poll': {
          const option = data?.option ?? data?.selected ?? data?.value ?? 'unknown';
          const totalVotes = data?.totalVotes ?? data?.votes ?? null;
          const question = title || data?.question || 'Poll';
          return totalVotes != null
            ? `New vote on "${question}": ${option} selected (now at ${totalVotes} votes total)`
            : `New vote on "${question}": ${option} selected`;
        }
        case 'feedback-form': {
          const rating = data?.rating ?? data?.stars ?? null;
          const comment = data?.comment ?? data?.feedback ?? data?.text ?? '';
          const ratingStr = rating != null ? `${rating}/5 stars` : '';
          const commentStr = comment ? ` — "${comment}"` : '';
          return `New feedback received${ratingStr ? ': ' + ratingStr : ''}${commentStr}`;
        }
        case 'approval-flow': {
          const action = data?.action ?? data?.decision ?? data?.status ?? 'unknown';
          const approver = data?.approver ?? data?.name ?? data?.user ?? 'someone';
          return `Item ${action} by ${approver}`;
        }
        case 'checkout': {
          const total = data?.total ?? data?.amount ?? null;
          return total != null
            ? `Checkout completed ($${total})`
            : 'Checkout completed';
        }
        case 'shopping-list': {
          const checked = data?.checkedCount ?? data?.completed ?? null;
          const total = data?.totalCount ?? data?.total ?? null;
          return checked != null && total != null
            ? `Shopping list updated: ${checked}/${total} items checked`
            : 'Shopping list updated';
        }
        default: {
          const summary = data ? JSON.stringify(data).slice(0, 120) : '';
          return `[SparkUI] Completion on "${pageLabel}"${summary ? ': ' + summary : ''}`;
        }
      }
    }

    /**
     * Handle a SparkUI event from the server's in-process event bus.
     * Routes completion events back to the originating chat session.
     */
    function handleSparkuiEvent(evt) {
      const { pageId, type } = evt;

      // Only route completion events back to chat
      if (type !== 'completion') return;

      const sessionInfo = pageSessionMap.get(pageId);
      const message = formatEventSummary(evt);

      if (sessionInfo && api.sendMessage) {
        api.sendMessage({
          text: message,
          sessionId: sessionInfo.sessionId,
          channelId: sessionInfo.channelId,
        }).catch((err) => {
          api.log?.warn?.(`SparkUI: failed to route event to session: ${err.message}`);
        });
      } else if (api.sendMessage) {
        // No session tracked (page created outside plugin tools) — broadcast
        api.sendMessage({ text: message }).catch((err) => {
          api.log?.warn?.(`SparkUI: failed to send event message: ${err.message}`);
        });
      } else {
        // api.sendMessage not available — log for debugging
        // TODO(#422): OpenClaw plugin SDK does not expose sendMessage yet.
        // When it does, remove this fallback. For now, log the event.
        api.log?.info?.(`SparkUI completion event (no sendMessage API): ${message}`);
      }
    }
  },
});
